# Generated by Django 4.1.5 on 2023-01-03 04:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('testapp', '0002_tablemaster'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_name', models.CharField(max_length=40)),
                ('role', models.CharField(choices=[('Manager', 'Manager'), ('TeamLeader', 'TeamLeader'), ('SeniorAgent', 'SeniorAgent'), ('JuniorAgent', 'JuniorAgent')], default='JuniorAgent', max_length=40)),
                ('email_address', models.EmailField(max_length=100)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReportMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_name', models.CharField(max_length=100)),
                ('pre_report_function_name', models.CharField(max_length=100)),
                ('extra_detail', models.TextField(editable=False)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('report_generated_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='user_id', to=settings.AUTH_USER_MODEL)),
                ('table_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tn', to='testapp.tablemaster')),
            ],
        ),
    ]
